const ProjectList = [
  {
    id: "0",
    name: "Timberland shop",
    status: "Ready",
    image: "https://i.ibb.co/ctkVrZG/project-1.jpg",
    linkDeploy: "https://exigoll.github.io/timberland/",
    linkDev: "https://github.com/Exigoll/timberland",
    type: "SPA",
    skills: "React, REST API, SCSS",
  },
  {
    id: "1",
    name: "My first portfolio",
    status: "Ready",
    image: "https://i.ibb.co/wrtW7Yj/project-2.jpg",
    linkDeploy: "https://exigoll.github.io/CV/",
    linkDev: "https://github.com/Exigoll/CV",
    type: "Landing page",
    skills: "JS Vanilla, HTML, SCSS",
  },
  {
    id: "2",
    name: "This portfolio",
    status: "Ready",
    image: "https://i.ibb.co/pxtBLJp/project-4.jpg",
    linkDeploy: "https://exigoll.github.io/portfolio-react/",
    linkDev: "https://github.com/Exigoll/portfolio-react",
    type: "SPA",
    skills: "React, SCSS",
  },
  {
    id: "3",
    name: "Clone VK",
    status: "In work",
    image: "https://i.ibb.co/28w1TL3/project-3.jpg",
    linkDeploy: "https://exigoll.github.io/ssss",
    linkDev: "https://github.com/Exigoll/ssss",
    type: "SPA",
    skills: "React, SCSS",
  },
  {
    id: "4",
    name: "Calculator TS",
    status: "Ready",
    image: "https://i.ibb.co/F5QyBxF/project-5.png",
    linkDeploy: "https://exigoll.github.io/calculator-TS/",
    linkDev: "https://github.com/Exigoll/calculator-TS",
    type: "SPA",
    skills: "React, TypeScript, StyledComponent",
  },
  {
    id: "5",
    name: "GH-search",
    status: "Ready",
    image: "https://i.ibb.co/2ZmvTZf/project-6.png",
    linkDeploy: "https://exigoll.github.io/gh-search",
    linkDev: "https://github.com/Exigoll/gh-search",
    type: "SPA",
    skills: "React, Redux, TypeScript, TailWind",
  },
];

export default ProjectList;
