const ProjectList = [
  {
    id: "0",
    name: "Timberland shop",
    status: "Ready",
    image: "https://i.ibb.co/ctkVrZG/project-1.jpg",
    linkDeploy: "https://exigoll.github.io/timberland/",
    linkDev: "https://github.com/Exigoll/timberland",
    type: "SPA",
    skills: "React, REST API, Styled-components",
  },
  {
    id: "1",
    name: "My first portfolio",
    status: "Ready",
    image: "https://i.ibb.co/wrtW7Yj/project-2.jpg",
    linkDeploy: "https://exigoll.github.io/CV/",
    linkDev: "https://github.com/Exigoll/CV",
    type: "Landing page",
    skills: "JS Vanilla, HTML, SCSS",
  },
  {
    id: "2",
    name: "This portfolio",
    status: "Ready",
    image: "https://i.ibb.co/pxtBLJp/project-4.jpg",
    linkDeploy: "https://exigoll.github.io/portfolio/",
    linkDev: "https://github.com/Exigoll/portfolio",
    type: "SPA",
    skills: "React, CSS Modules",
  },
  {
    id: "3",
    name: "Calculator",
    status: "Ready",
    image: "https://i.ibb.co/F5QyBxF/project-5.png",
    linkDeploy: "https://exigoll.github.io/calculator/",
    linkDev: "https://github.com/Exigoll/calculator",
    type: "SPA",
    skills: "React, TypeScript, Styled-components",
  },
  {
    id: "4",
    name: "Netflix",
    status: "In work",
    image: "https://i.ibb.co/sscDfPh/project-4.png",
    linkDeploy: "https://netflix-next-ts.vercel.app/",
    linkDev: "https://github.com/Exigoll/netflix",
    type: "SPA",
    skills: "Next.js, TypeScript, Tailwind, REST API",
  },
  {
    id: "5",
    name: "Cafe: PizzaMan",
    status: "In work",
    image: "https://i.ibb.co/YDkkHVy/project-6.png",
    linkDeploy: "https://exigoll.github.io/pizzaman",
    linkDev: "https://github.com/Exigoll/pizzaman",
    type: "SPA",
    skills: "React, TypeScript, CSS Modules, REST API",
  },
];

export default ProjectList;
